[build-system]
requires=[
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.23",
]
build-backend = "setuptools.build_meta"

[tool.mypy]
files = "setup.py"
python_version = "3.10"

[tool.cibuildwheel]
before-build = "rm -rf {project}/build"
